## 1: Importando as bibliotecas

In [3]:
# Importando as bibliotecas necessárias
import pandas as pd

## 2: Avaliando os dataframes

In [ ]:
# Importando os arquivos CSV para DataFrames do Pandas
df_customers = pd.read_csv("Dataset_Original\\olist_customers_dataset.csv")
df_geolocation = pd.read_csv("Dataset_Original\\olist_geolocation_dataset.csv")
df_items = pd.read_csv("Dataset_Original\\olist_order_items_dataset.csv")
df_payments = pd.read_csv("Dataset_Original\\olist_order_payments_dataset.csv")
df_reviews = pd.read_csv("Dataset_Original\\olist_order_reviews_dataset.csv")
df_orders = pd.read_csv("Dataset_Original\\olist_orders_dataset.csv")
df_products = pd.read_csv("Dataset_Original\\olist_products_dataset.csv")
df_sellers = pd.read_csv("Dataset_Original\\olist_sellers_dataset.csv")

In [5]:
# Criando um dicionário para facilitar a análise
dfs = {
    'customers':   df_customers,
    'geolocation': df_geolocation,
    'items':       df_items,
    'payments':    df_payments,
    'reviews':     df_reviews,
    'orders':      df_orders,
    'products':    df_products,
    'sellers':     df_sellers,
}

In [6]:
# Criando uma tabela com o resumo de duplicatas e nulos
resumo = pd.DataFrame([
    {
        'dataset':          nome,
        'total_linhas':     len(df),
        'duplicatas':       df.duplicated().sum(),
        'dup_%':            round(df.duplicated().sum() / len(df) * 100, 2),
        'colunas_c_nulo':   (df.isnull().sum() > 0).sum(),
        'total_nulos':      df.isnull().sum().sum(),
        'nulos_%':          round(df.isnull().sum().sum() / df.size * 100, 2)
    }
    for nome, df in dfs.items()
])

resumo

,dataset,total_linhas,duplicatas,dup_%,colunas_c_nulo,total_nulos,nulos_%
0,customers,99441,0,0.00,0,0,0.00
1,geolocation,1000163,261831,26.18,0,0,0.00
2,items,112650,0,0.00,0,0,0.00
3,payments,103886,0,0.00,0,0,0.00
4,reviews,99224,0,0.00,2,145903,21.01
5,orders,99441,0,0.00,3,4908,0.62
6,products,32951,0,0.00,8,2448,0.83
7,sellers,3095,0,0.00,0,0,0.00

## 3: Analisando e limpando o dataframe de geolocalização

In [7]:
# Visualizando as primeiras linhas do dataframe de geolocalização
dfs['geolocation'].head()

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP
2,1046,-23.546129,-46.642951,sao paulo,SP
3,1041,-23.544392,-46.639499,sao paulo,SP
4,1035,-23.541578,-46.641607,sao paulo,SP

In [8]:
# Removendo as colunas de latitude e longitude
dfs['geolocation'].drop(columns=['geolocation_lat', 'geolocation_lng'], inplace=True)

In [9]:
# Retirando as linhas duplicadas do dataframe de geolocalização
dfs['geolocation'].drop_duplicates(inplace=True)

#Confirmando que não existem mais linhas duplicadas no dataframe de geolocalização.
dfs['geolocation'].duplicated().sum()

np.int64(0)

## 4: Analisando o dataframe de reviews

In [10]:
# Visualizando as primeiras linhas do dataframe de reviews
dfs['reviews'].head() # Existem informações nulas, mas o que é importante é que a nota da avaliação.

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53

In [11]:
# Verificando a quantidade de nulos na coluna de nota da avaliação
dfs['reviews']['review_score'].isnull().sum() # Não existem nulos na coluna de nota da avaliação.

np.int64(0)

## 5: Analisando o dataframe de ordens

In [12]:
# Visualizando as primeiras linhas do dataframe de ordens
dfs['orders'].head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [13]:
# Verificando colunas com nulos no dataframe de ordens
dfs['orders'].isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [14]:
# Verificando as linhas que possuem nulos na coluna de data de entrega
dfs['orders'][dfs['orders']['order_delivered_customer_date'].isnull()]

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
6,136cce7faa42fdb2cefd53fdc79a6098,ed0271e0b7da060a393796590e7b737a,invoiced,2017-04-11 12:22:08,2017-04-13 13:25:17,NaN,NaN,2017-05-09 00:00:00
44,ee64d42b8cf066f35eac1cf57de1aa85,caded193e8e47b8362864762a83db3c5,shipped,2018-06-04 16:44:48,2018-06-05 04:31:18,2018-06-05 14:32:00,NaN,2018-06-28 00:00:00
103,0760a852e4e9d89eb77bf631eaaf1c84,d2a79636084590b7465af8ab374a8cf5,invoiced,2018-08-03 17:44:42,2018-08-07 06:15:14,NaN,NaN,2018-08-21 00:00:00
128,15bed8e2fec7fdbadb186b57c46c92f2,f3f0e613e0bdb9c7cee75504f0f90679,processing,2017-09-03 14:22:03,2017-09-03 14:30:09,NaN,NaN,2017-10-03 00:00:00
154,6942b8da583c2f9957e990d028607019,52006a9383bf149a4fb24226b173106f,shipped,2018-01-10 11:33:07,2018-01-11 02:32:30,2018-01-11 19:39:23,NaN,2018-02-07 00:00:00
...,...,...,...,...,...,...,...,...
99283,3a3cddda5a7c27851bd96c3313412840,0b0d6095c5555fe083844281f6b093bb,canceled,2018-08-31 16:13:44,NaN,NaN,NaN,2018-10-01 00:00:00
99313,e9e64a17afa9653aacf2616d94c005b8,b4cd0522e632e481f8eaf766a2646e86,processing,2018-01-05 23:07:24,2018-01-09 07:18:05,NaN,NaN,2018-02-06 00:00:00
99347,a89abace0dcc01eeb267a9660b5ac126,2f0524a7b1b3845a1a57fcf3910c4333,canceled,2018-09-06 18:45:47,NaN,NaN,NaN,2018-09-27 00:00:00
99348,a69ba794cc7deb415c3e15a0a3877e69,726f0894b5becdf952ea537d5266e543,unavailable,2017-08-23 16:28:04,2017-08-28 15:44:47,NaN,NaN,2017-09-15 00:00:00
99415,5fabc81b6322c8443648e1b21a6fef21,32c9df889d41b0ee8309a5efb6855dcb,unavailable,2017-10-10 10:50:03,2017-10-14 18:35:57,NaN,NaN,2017-10-23 00:00:00

In [15]:
# Verificando as linhas que possuem nulos na coluna de data de entrega e que possuem o status de "delivered" (entregue)
dfs['orders'][dfs['orders']['order_delivered_customer_date'].isnull()][dfs['orders']['order_status'].str.contains('delivered')] # Existem 8 ordens que possuem o status de "entregue", mas não possuem a data de entrega.

C:\Users\João\AppData\Local\Temp\ipykernel_2864\3937328017.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  dfs['orders'][dfs['orders']['order_delivered_customer_date'].isnull()][dfs['orders']['order_status'].str.contains('delivered')] # Existem 8 ordens que possuem o status de "entregue", mas não possuem a data de entrega.

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
3002,2d1e2d5bf4dc7227b3bfebb81328c15f,ec05a6d8558c6455f0cbbd8a420ad34f,delivered,2017-11-28 17:44:07,2017-11-28 17:56:40,2017-11-30 18:12:23,NaN,2017-12-18 00:00:00
20618,f5dd62b788049ad9fc0526e3ad11a097,5e89028e024b381dc84a13a3570decb4,delivered,2018-06-20 06:58:43,2018-06-20 07:19:05,2018-06-25 08:05:00,NaN,2018-07-16 00:00:00
43834,2ebdfc4f15f23b91474edf87475f108e,29f0540231702fda0cfdee0a310f11aa,delivered,2018-07-01 17:05:11,2018-07-01 17:15:12,2018-07-03 13:57:00,NaN,2018-07-30 00:00:00
79263,e69f75a717d64fc5ecdfae42b2e8e086,cfda40ca8dd0a5d486a9635b611b398a,delivered,2018-07-01 22:05:55,2018-07-01 22:15:14,2018-07-03 13:57:00,NaN,2018-07-30 00:00:00
82868,0d3268bad9b086af767785e3f0fc0133,4f1d63d35fb7c8999853b2699f5c7649,delivered,2018-07-01 21:14:02,2018-07-01 21:29:54,2018-07-03 09:28:00,NaN,2018-07-24 00:00:00
92643,2d858f451373b04fb5c984a1cc2defaf,e08caf668d499a6d643dafd7c5cc498a,delivered,2017-05-25 23:22:43,2017-05-25 23:30:16,NaN,NaN,2017-06-23 00:00:00
97647,ab7c89dc1bf4a1ead9d6ec1ec8968a84,dd1b84a7286eb4524d52af4256c0ba24,delivered,2018-06-08 12:09:39,2018-06-08 12:36:39,2018-06-12 14:10:00,NaN,2018-06-26 00:00:00
98038,20edc82cf5400ce95e1afacc25798b31,28c37425f1127d887d7337f284080a0f,delivered,2018-06-27 16:09:12,2018-06-27 16:29:30,2018-07-03 19:26:00,NaN,2018-07-19 00:00:00

## 6: Analisando o dataframe de produtos

In [16]:
# Visualizando as primeiras linhas do dataframe de produtos
dfs['products'].head(10)

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0
5,41d3672d4792049fa1779bb35283ed13,instrumentos_musicais,60.0,745.0,1.0,200.0,38.0,5.0,11.0
6,732bd381ad09e530fe0a5f457d81becb,cool_stuff,56.0,1272.0,4.0,18350.0,70.0,24.0,44.0
7,2548af3e6e77a690cf3eb6368e9ab61e,moveis_decoracao,56.0,184.0,2.0,900.0,40.0,8.0,40.0
8,37cc742be07708b53a98702e77a21a02,eletrodomesticos,57.0,163.0,1.0,400.0,27.0,13.0,17.0
9,8c92109888e8cdf9d66dc7e463025574,brinquedos,36.0,1156.0,1.0,600.0,17.0,10.0,12.0

In [17]:
# Verificando colunas com nulos no dataframe de produtos
dfs['products'].isnull().sum()

product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

In [18]:
# Verificando as linhas que possuem nulos na coluna de categoria
dfs['products'][dfs['products']['product_category_name'].isnull()]

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
105,a41e356c76fab66334f36de622ecbd3a,NaN,NaN,NaN,NaN,650.0,17.0,14.0,12.0
128,d8dee61c2034d6d075997acef1870e9b,NaN,NaN,NaN,NaN,300.0,16.0,7.0,20.0
145,56139431d72cd51f19eb9f7dae4d1617,NaN,NaN,NaN,NaN,200.0,20.0,20.0,20.0
154,46b48281eb6d663ced748f324108c733,NaN,NaN,NaN,NaN,18500.0,41.0,30.0,41.0
197,5fb61f482620cb672f5e586bb132eae9,NaN,NaN,NaN,NaN,300.0,35.0,7.0,12.0
...,...,...,...,...,...,...,...,...,...
32515,b0a0c5dd78e644373b199380612c350a,NaN,NaN,NaN,NaN,1800.0,30.0,20.0,70.0
32589,10dbe0fbaa2c505123c17fdc34a63c56,NaN,NaN,NaN,NaN,800.0,30.0,10.0,23.0
32616,bd2ada37b58ae94cc838b9c0569fecd8,NaN,NaN,NaN,NaN,200.0,21.0,8.0,16.0
32772,fa51e914046aab32764c41356b9d4ea4,NaN,NaN,NaN,NaN,1300.0,45.0,16.0,45.0
32852,c4ceee876c82b8328e9c293fa0e1989b,NaN,NaN,NaN,NaN,700.0,28.0,3.0,43.0

In [19]:
#Retirando as linhas com nulos na coluna de categoria do dataframe de produtos
dfs['products'].dropna(subset=['product_category_name'], inplace=True)

In [20]:
# Confirmando que não existem mais nulos na coluna de categoria
dfs['products'].isnull().sum()

product_id                    0
product_category_name         0
product_name_lenght           0
product_description_lenght    0
product_photos_qty            0
product_weight_g              1
product_length_cm             1
product_height_cm             1
product_width_cm              1
dtype: int64

## 7: Exportando os dataframes corrigidos

In [22]:
# Exportando os DataFrames limpos para arquivos Excel
for nome, df in dfs.items():
    df.to_excel(f'Dataset_corrigido/{nome}.xlsx', sheet_name=nome, index=False)
    print(f'✅ {nome}.xlsx exportado!')

print('✅✅ Todos os arquivos exportados!✅✅')

✅ customers.xlsx exportado!
✅ geolocation.xlsx exportado!
✅ items.xlsx exportado!
✅ payments.xlsx exportado!
✅ reviews.xlsx exportado!
✅ orders.xlsx exportado!
✅ products.xlsx exportado!
✅ sellers.xlsx exportado!
✅✅ Todos os arquivos exportados!✅✅